apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: hello-gway
  annotations: # Flux annotions are not required for prod as we have to change the build number manually
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.nginx: glob:build-*
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: us-west1-docker.pkg.dev/innate-setup-341509/gateway-repo/hello-node:v10
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  namespace: hello-gway
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080